// This is the default configuration for the Popcorn Maker server
// You shouldn't edit this file. Instead, look at the README for
// various configuration options

module.exports = {
  // APP_HOSTNAME must match the address in your browser's URL bar
  // If it does not, then Persona sign-in will not work
  // Don't add any trailing slashes, just protocol://APP_HOSTNAME[:port]
  "APP_HOSTNAME": "https://sheltered-shore-3085.herokuapp.com",
  "OPTIMIZE_JS": false,
  "OPTIMIZE_CSS": false,
  "FORCE_SSL": true,
  "DEBUG": true,

  // PORT is the port that the server will bind to
  // PORT is all caps because all the PaaS providers do it this way

  "PORT": 5000,

  "MAKE_ENDPOINT": "http://immense-ravine-8501.herokuapp.com",

  // make authentication - private and public keys must be generated by the MakeAPI
  "MAKE_PRIVATEKEY": "00000000-0000-0000-000000000000",
  "MAKE_PUBLICKEY": "00000000-0000-0000-000000000000",

  "JWPLAYER_KEY": "zaIF4JI9EeK2FSIACpYGxA",

  "LOGIN_SERVER_URL_WITH_AUTH": "https://testuser:password@sleepy-badlands-6817.herokuapp.com",

  "LOGIN_SERVER_URL": "https://sleepy-badlands-6817.herokuapp.com",

  "AUDIENCE": "http://polar-falls-6251.herokuapp.com",

  "GA_ACCOUNT": "",
  "GA_DOMAIN": "",

  // i18n
  "SUPPORTED_LANGS": [
    "*"
  ],

  "EMBED_HOSTNAME": "",

  // Domain to host user subdomains on
  // Must be in the format protocol://hostname[:port]
  "USER_SUBDOMAIN": "",

  "TOGETHERJS": "http://localhost:8811",
  "NODE_HUBBLE_ENDPOINT": "http://node-hubble.mofostaging.net/",
  "CLYP_ENDPOINT": "https://apistaging.clyp.it",

  "TOGETHERJS_ENABLED": false,

  "S3_KEY": "AKIAIPWF7Q36NHBE45NA",
  "S3_BUCKET": "webmakerpopcorn",
  "S3_SECRET": "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",
  "S3_DOMAIN": "http://localhost:12319",
  "S3_EMULATION": false,

  "MOX_PORT": 12319,

  // API Keys for Media Sync
  "SYNC_SOUNDCLOUD": "PRaNFlda6Bhf5utPjUsptg",
  "SYNC_FLICKR": "b939e5bd8aa696db965888a31b2f1964",
  // Public API Key
  "SYNC_GIPHY": "dc6zaTOxFJmzC",
  "SYNC_LIMIT": 20,

  "logger" : {
    "format" : "dev"
  },
  "SECRET": "dummy secret value",
  "staticMiddleware": {
    "maxAge": "0"
  },
  "database": {
    "database": "heroku_36b9fc84e34a81d", //masked
    "username": "bc5e0f625eb3fd", //masked
    "password":  "acf7c9b0", //masked
    "options": {
      "host":"us-cdbr-iron-east-02.cleardb.net",
      "post":3306,
      "logging": false,
      "dialect": "mysql",
      "storage": "popcorn.mysql",
      "define": {
        "charset": "utf8",
        "collate": "utf8_general_ci"
      }
    }
  },
  "ENABLE_GELF_LOGS": false
};
